version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - wpnet
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wp
      - MYSQL_PASSWORD=wp
      - MYSQL_ROOT_PASSWORD=root

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./html:/var/www/html
      - ./scripts:/tmp/scripts
    ports:
      - '8080:80'
    depends_on:
      - db
    networks:
      - wpnet

  cli:
    image: wordpress:cli-2.4.0-php7.4
    volumes_from: 
      - app:rw
    networks:
      - wpnet

networks:
  wpnet:

